language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

before_script:
  - npm install -g --silent @angular/cli@11.0.5

install:
  - npm install

script:
  - ng test
  - ng lint
  - ng build
