language: node_js
node_js:
  - "10"
dist: trusty
sudo: required

addons:
  chrome: stable
  sonarcloud:
    organization: "aboudard"

cache:
  directories:
     - ./node_modules

before_script:
  - npm install -g --silent @angular/cli@11.0.5

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
